### ISSUE TITLE
Assign host after finish

### ISSUE THREAD

**Issue by hubertbert** [kadrim/zoom-breakout#1]
Really nice work, got one tiny feature request =D
If the bot would assign the first user it the participants list as host after the rooms are created that would be perfect. (if this is actual possible)
The wait till the bot is gone it not to long but if the host would be assigned then you could directly go on with any manual things you want to to do.

**Comment by kadrim** [comment]
should be possible by just logging out after finishing. that would require that at least one other user is present in the meeting.

next slackday i might have the time to have a look into it ;-)
